project_id = "xikvfybxthvqhpjbrszp"

[functions.buscar-fechamentos]
verify_jwt = false

[functions.registrar-fechamento]
verify_jwt = false

[functions.buscar-boleto-pdf]
verify_jwt = false

[functions.processar-creditos-bloqueados]
verify_jwt = false

[functions._cron.processar-creditos]
verify_jwt = false

[functions.banco-inter-create-charge]
verify_jwt = false

[functions.banco-inter-webhook]
verify_jwt = false

[functions.banco-inter-configure-webhook]
verify_jwt = true

[functions.buscar-extrato]
verify_jwt = false

[functions.buscar-recargas]
verify_jwt = false

[functions.buscar-remetentes]
verify_jwt = false

[functions.criar-cliente-autocadastro]
verify_jwt = false

[functions.criar-remetente-autocadastro]
verify_jwt = false

[functions.sincronizar-remetentes]
verify_jwt = false

[functions.processar-fechamento-fatura]
verify_jwt = false

[functions.banco-inter-create-boleto]
verify_jwt = false

[functions.cancelar-etiqueta-admin]
verify_jwt = false

[functions.corrigir-consumos-incorretos]
verify_jwt = false

[functions.nuvemshop-oauth-token]
verify_jwt = false

[functions.nuvemshop-webhook]
verify_jwt = false

[functions.processar-pedido-nuvemshop]
verify_jwt = false

[functions.cotacao-frete]
verify_jwt = false

[functions.atualizar-transportadora-cliente]
verify_jwt = false

[functions.buscar-participantes-promocao]
verify_jwt = false

[functions.registrar-acesso]
verify_jwt = false

[functions.atualizar-presenca]
verify_jwt = false

[functions.buscar-logs-acesso]
verify_jwt = false

[functions.emitir-etiqueta]
verify_jwt = false

[functions.sincronizar-remetente-para-api]
verify_jwt = false

[functions.adicionar-saldo-manual]
verify_jwt = false

[functions.gerar-fatura-exemplo]
verify_jwt = false
