project_id = "xikvfybxthvqhpjbrszp"

[functions.banco-inter-create-charge]
verify_jwt = false

[functions.banco-inter-webhook]
verify_jwt = false

[functions.banco-inter-configure-webhook]
verify_jwt = true

[functions.buscar-extrato]
verify_jwt = false

[functions.buscar-recargas]
verify_jwt = false

[functions.buscar-remetentes]
verify_jwt = false

[functions.criar-cliente-autocadastro]
verify_jwt = false